name: Upload Release Asset

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  release-net:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/CodeButler

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100   

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish
      run: dotnet publish ./CodeButler.Console/CodeButler.Console.csproj --output ./publish

    - name: Upload Console Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CodeButler.Console
        path: ${{ github.workspace }}/src/CodeButler/publish/

  release-extension:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/projektanker.code-butler
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100 

    - name: Install NPM packages
      run: npm install

    - name: Package VSIX
      run: npm run vsce:package

    - name: Upload VSIX Artifact
      uses: actions/upload-artifact@v2
      with:
        name: projektanker.code-butler
        path: ${{ github.workspace }}/src/projektanker.code-butler/code-butler-0.0.1.vsix